name: "Start installer on tty1"
stages:
    initramfs:
     - if: |
            cat /proc/cmdline | grep -q "nodepair.enable"
       commands:
       - systemctl disable getty@tty1
       - systemctl enable kairos
       - systemctl enable kairos-webui
    # Starts installer on boot in Alpine and openRC based
     - if: |
            cat /proc/cmdline | grep -q "nodepair.enable"
       commands:
       - sed -i -e 's/tty1.*//g' /etc/inittab
       - echo "tty1::respawn:/usr/bin/kairos-agent install" >> /etc/inittab
     - if: |
            cat /proc/cmdline | grep -q "interactive-install"
       commands:
       - systemctl disable getty@tty1
       - systemctl enable kairos-interactive
       - systemctl enable kairos-webui
    # Starts installer on boot in Alpine and openRC based
     - if: |
            cat /proc/cmdline | grep -q "interactive-install"
       commands:
       - sed -i -e 's/tty1.*//g' /etc/inittab
       - echo "tty1::respawn:/usr/bin/kairos-agent interactive-install --shell" >> /etc/inittab
       - rc-service kairos-webui start